on: [workflow_call]
defaults:
  run:
    shell: bash

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        cache-dependency-path: go.sum
        with:
          go-version-file: go.mod
      - run: go version
      - name: install deps
        run: go mod tidy