on: [workflow_call]
defaults:
  run:
    shell: bash

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deps
        run: |
          echo "Running deps script"