on: [workflow_call]
defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Go and dependencies
        uses: ./.github/actions/setup-go-and-deps

      - name: download builded artifact
        uses: actions/download-artifact@v2
        with:
          name: main
      
      - name: Deploy
        run: |
          echo "Dummy Deploy..."