on: [workflow_call]
defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golang ci lint
        uses: golangci/golangci-lint-action@v6
        continue-on-error: true
        with:
          version: latest
          args: --timeout 10m
        
          