on: [workflow_call]
defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Go and dependencies
        uses: ./.github/actions/setup-go-and-deps
      - name: test
        run: go test -v ./...
        env:
          AUTH_JWT_SECRET: OjOHjJs1VvhuzIWqttTtNh7Y81xKgDatiopCUKMoKL0StwMb/LsBQLJ+AM6zq6WbherxmJGtPncQ3OsWPHdOTw==
